  # # Configuration file for Ojo build monitoring tool
  # -
  #   servertype: Go
  #   url: http://10.1.1.2:8153/go/cctray.xml
  #   username: 
  #   password: 
  #   pipelines:
  #     -
  #       name: "Trunk :: spec"
  -